spring:
  redis:
    connect-timeout: 6000
    cluster:
      max-redirects: 3
      nodes:
        - 192.168.28.1:7001
        - 192.168.28.1:7002
        - 192.168.28.1:7003
        - 192.168.28.1:7004
        - 192.168.28.1:7005
        - 192.168.28.1:7006
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: -1
